### ISSUE TITLE
为啥会这样，求大佬指点

### ISSUE THREAD

**Issue by whyshame** [gc-toolkit/GenshinLauncher#10]
![2AE4DDB3EECB511D6A021AE0FB7BAA24](https://user-images.githubusercontent.com/115207827/194480107-1da8b209-5589-4138-ad7c-451749982bf2.jpg)

**Comment by whyshame** [comment]
就是打不开文件

**Comment by SwetyCore** [comment]
把启动器用管理员权限打开试试

**Comment by SwetyCore** [comment]
同 #9
