### ISSUE TITLE
一些建议和几个问题

### ISSUE THREAD

**Issue by FISHandCHEAP** [gc-toolkit/GenshinLauncher#11]
1.Launcher主程序的名字是MainWindow，很明显是忘记改名啦！
2.主程序没有图标，希望可以加上
3.开启仅代理之后，“开始游戏”的按钮建议自动变成“开启代理”，这样更明确
4.左边的活动图有点鸡肋，建议拓展可自定义的范围，比如设置点击之后打开链接，或者直接取消显示

**Comment by FISHandCHEAP** [comment]
问题：转代理的具体链接看不到，建议让用户可修改

**Comment by SwetyCore** [comment]
1.是的
2.暂时没找到合适的图标
3.好建议
4.本来是想自定义的，但是看起来没什么人用这个启动器，我就没整那么多花哨的东西了
