### ISSUE TITLE
支持设置要连接的grasscutter服务器地址

### ISSUE THREAD

**Issue by karma-sun** [gc-toolkit/GenshinLauncher#13]
支持设置要连接的grasscutter服务器地址，类似Cultivation那样

**Comment by SwetyCore** [comment]
设置页面就有

**Comment by karma-sun** [comment]
> 设置页面就有

服务器不能用非默认端口吗?
如服务器是1.2.3.4 ,端口12345
尝试在地址那一项填写1.2.3.4:12345,并不能连上

**Comment by SwetyCore** [comment]
> > 设置页面就有
> 
> 服务器不能用非默认端口吗? 如服务器是1.2.3.4 ,端口12345 尝试在地址那一项填写1.2.3.4:12345,并不能连上

可以使用。
如果不能，请检查配置或者在Discord私信我具体内容
