### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by hwbhuai** [gc-toolkit/GenshinLauncher#14]
![1](https://user-images.githubusercontent.com/116620457/197688123-fbf0cbb0-11a5-4480-9095-91f3efea0ba3.jpg)
![2](https://user-images.githubusercontent.com/116620457/197688138-1a760c92-9f67-4c34-9471-06198d108414.jpg)
这种情况怎么办？求助大佬

**Comment by hwbhuai** [comment]
和15那个err.log帖子一样，不知道怎么解决，有文件检测不到存在

**Comment by SwetyCore** [comment]
和 #15 重复了
