### ISSUE TITLE
UA补丁点过之后还是{官方}，没有显示已打补丁

### ISSUE THREAD

**Issue by Cx330cao** [gc-toolkit/GenshinLauncher#16]
![image](https://user-images.githubusercontent.com/117246515/199384728-ae38e3ab-5902-494c-a1df-ad7ff5285bea.png)
![image](https://user-images.githubusercontent.com/117246515/199384773-ec3e460c-1b14-48d6-8955-641d90e6b045.png)

**Comment by SwetyCore** [comment]
已经在新版本中尝试修复修复
