### ISSUE TITLE
Metadata补丁 提示: 找不到pkg_version文件

### ISSUE THREAD

**Issue by bilibili20001** [gc-toolkit/GenshinLauncher#4]
![bug](https://user-images.githubusercontent.com/70944645/187438143-a29b8a0b-389b-457c-84ae-84817e0a925a.jpg)

**Comment by SwetyCore** [comment]
此文件为补丁必须
缺少则无法正常打补丁

**Comment by SwetyCore** [comment]
你可以自行打补丁继续使用

**Comment by lanjuzi** [comment]
这个好像是海外版判断路径逻辑错误

`File.Exists(Path.Combine(GameExePath, "GenshinImpact_Data"))` 

替换成

`Directory.Exists(Path.Combine(Path.GetDirectoryName(GameExePath), "GenshinImpact_Data"))` 

就可以了

**Comment by bilibili20001** [comment]
> 

没找到在哪里换，大佬可以说一下吗？感谢

**Comment by SwetyCore** [comment]
> 这个好像是海外版判断路径逻辑错误
> 
> `File.Exists(Path.Combine(GameExePath, "GenshinImpact_Data"))`
> 
> 替换成
> 
> `Directory.Exists(Path.Combine(Path.GetDirectoryName(GameExePath), "GenshinImpact_Data"))`
> 
> 就可以了

也许？
但是我没有国际版的客户端

**Comment by lanjuzi** [comment]
`GameInfo.cs` 里面的  `GameExePath` 是指向 `.exe` 文件的绝对路径，`Path.Combine(GameExePath, "GenshinImpact_Data")` 后的路径是不对的，这里返回的类型默认就是 `GameType.UnKnown` 所以就会按照国内版本的去检查，导致国际版检测不到 `pkg_version` 文件。

另外就是 `File.Exists` 没法判断目录，换成 `Directory.Exists` 就能正常工作了。
