### ISSUE TITLE
登录时显示404网络繁忙

### ISSUE THREAD

**Issue by youthWorld** [gc-toolkit/GenshinLauncher#5]
![question](https://user-images.githubusercontent.com/111473465/188308431-09953e46-7e8e-4f90-9163-a220d55c83b3.png)

![question (2)](https://user-images.githubusercontent.com/111473465/188308500-bca6fd17-8b5e-443f-9de0-908ff4f6a22a.png)

**Comment by SwetyCore** [comment]
你并没有正确填写代理地址或者无法访问该服务器
请确保状态里的数据不为N/A

**Comment by youthWorld** [comment]
> 你并没有正确填写代理地址或者无法访问该服务器 请确保状态里的数据不为N/A

难道客户端自带的代理地址是无效需要更改的吗？

**Comment by SwetyCore** [comment]
> > 你并没有正确填写代理地址或者无法访问该服务器 请确保状态里的数据不为N/A
> 
> 难道客户端自带的代理地址是无效需要更改的吗？

是的，你需要自行寻找可用服务器进行游玩

**Comment by youthWorld** [comment]
> > > 你并没有正确填写代理地址或者无法访问该服务器 请确保状态里的数据不为N/A
> > 
> > 
> > 难道客户端自带的代理地址是无效需要更改的吗？
> 
> 是的，你需要自行寻找可用服务器进行游玩

好的，明白了，谢谢啦
