### ISSUE TITLE
右上角的UI不能正常显示

### ISSUE THREAD

**Issue by SummerOfIce** [gc-toolkit/GenshinLauncher#6]
![Uploading QQ截图20220914131214.png…]()

**Comment by SummerOfIce** [comment]
![QQ截图20220914131214](https://user-images.githubusercontent.com/73223207/190065256-caf6f359-529a-4677-91ed-a2a7ce19bb17.png)

**Comment by SwetyCore** [comment]
非Win11需要安装字体:https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font
